### ISSUE TITLE
User Feedback: optimize navigation

### ISSUE THREAD

**Issue by xamplo** [xamplo/aspecx#122]
I got a feedback from 2 users who mentioned, that it should be very helpful to have an additional link to the rating page of the related group in "Groups" - "[Group Name]".

In addition, it would be helpful in case the navigation from the dashboard to the detail page could be optimized, for example a "show detail" button in the dashboard page 

![img_3251](https://cloud.githubusercontent.com/assets/22747157/24038261/f585df7e-0b00-11e7-851a-77e97d011ce7.PNG)

**Comment by ursmeier-mercatus** [comment]
We should discuss this on the phone. The reason why it is like this today
a) Navigation Groups -> Rating
The user must choose a rating date. If the is no open rating date, where should we navigate to?
Navigation just on the rating-overview-page is is not a huge gain.

b) Dashboard-Overview-Page -> Detail Page
This would disable the direct navigation to the dashboard-detail-page with the statistics. Instead you would always have a pop-up. This defeats the menu entry "Dashboards". 
We would then better delete the menu "Dashboards" since the use can navigate from Groups -> Dashboard.

Personally, I would not implement either one.

**Comment by xamplo** [comment]
Let us speak about it in our next call, as I see some benefits for the users, who are using the app only once a month for example. They are searching on group level to find the required actions.

**Comment by ursmeier-mercatus** [comment]
1.4.5
Added Navigation from Groups -> Ratings
Others "I refuse" ;-)
