### ISSUE TITLE
Overall rating should be renamed to "Overall Perception"

### ISSUE THREAD

**Issue by xamplo** [xamplo/aspecx#28]
The "Overall Rating" could suggest a aggregation of all ratings, but is a separate rate, in fact the overall perception of the performance and/or spirit of this group. Therefor the word "Overall Perception" or "Overall Perception since the last rate" could express this function better,

**Comment by ursmeier-mercatus** [comment]
It must be consistent with the rating page itself.
Current the user rates:
- Overall Rating
- Most+ Aspect
- Most- Aspect

The same terms are used in the Dashboard.
Long labels such as "Overall Perception since the last rating" won't fit (e.g. "Overall Perception sinc..."

Alternatives:
- Overall
- General
- Global

Probably "General" would be best, or what do you think?

**Comment by ursmeier-mercatus** [comment]
Will add extra text below blue titles. This solves the issue better.
![bildschirmfoto 2016-11-06 um 22 33 24](https://cloud.githubusercontent.com/assets/22747183/20041924/4b62a0ae-a471-11e6-928d-a84be1e9a5e0.png)

**Comment by xamplo** [comment]
I agree, general is the best and rather doesn't assume the aggregation of the rating data

**Comment by ursmeier-mercatus** [comment]
Done: General + extra text.
Relase: 0.8

Note: Internally the ratings are also renamed from Overall to General, to be consistent. But this invalidates all current data. This means before releasing 0.8 we have to reset the DB again.
