### ISSUE TITLE
Dashboard "All Ratings Absolute Figures" not meaningful 

### ISSUE THREAD

**Issue by xamplo** [xamplo/aspecx#39]
Constructive feedback rate: 3, 1
The sum of the rates per color is not meaningful. The value is 4: Is that only one rate with the value 4 or more rates, e.g. 4 rates of 1

Although the title is "Absolute" the number of rates is missing or each rate should have his own color

![2016-11-12 21_29_30-lonelyscreen airplay receiver](https://cloud.githubusercontent.com/assets/22747157/20240701/50a24da0-a91f-11e6-81dc-7447d6903d50.png)

**Comment by xamplo** [comment]
In addition the trends are not visible, as the time table is missing.

All data (4 aspects, 3 raters, 3 rate dates) are correct!

![2016-11-13 08_03_53-](https://cloud.githubusercontent.com/assets/22747157/20244196/dcc5278c-a977-11e6-805d-e7ee22af1475.png)

**Comment by xamplo** [comment]
Will be considered in a later version

**Comment by ursmeier-mercatus** [comment]
Changed negative aspects to negative scale: -10 + rating.
A rating of most negative aspect of 4 will result in -6.
This is not entirely correct, since it is not the user's rating. But the chart is more intuitive.
However, a smart user should ask why we display *negative* figures if all the ratings are always *positive*.
